BUN_DOCKER = docker run --rm -v $(PWD):/usr/src/app -w /usr/src/app oven/bun:1
PHP_RUN = docker compose run --rm --remove-orphans -w //var/www php
COMPOSER_DOCKER = docker run --rm -v $(PWD):/app composer:2.7.1

PORT ?= 8000

all: html test

.PHONY: deps
deps: node_modules vendor

node_modules: package.json
	$(BUN_DOCKER) bun install
	touch -m node_modules

vendor: composer.json
	$(COMPOSER_DOCKER) install --prefer-dist
	touch -m vendor

.PHONY: data
data: node_modules
	$(BUN_DOCKER) bun ./source-data/build.ts
	$(BUN_DOCKER) bun ./source-data/validate.ts

.PHONY: validate-data
validate-data: node_modules
	$(BUN_DOCKER) bun ./source-data/validate.ts

.PHONY: html
html: node_modules
	$(BUN_DOCKER) bun ./generate-html-dir.ts
	$(PHP_RUN) php ./generate-static.php

.PHONY: dev
dev: html
	docker compose run --rm --remove-orphans --service-ports -v "$(PWD)/dev-router.php:/var/www/dev-router.php" -w //var/www php php -S 0.0.0.0:$(PORT) -t html dev-router.php

.PHONY: test
test: validate-data bun-test check

.PHONY: bun-test
bun-test: node_modules
	$(BUN_DOCKER) bun test --dots

.PHONY: check
check: vendor
	$(COMPOSER_DOCKER) ./vendor/bin/phpcs --ignore=vendor,.dh-diag,html -n .

.PHONY: fix
fix: vendor
	$(COMPOSER_DOCKER) ./vendor/bin/phpcbf --ignore=vendor,.dh-diag,html -n .
